Add `get_desktop_display_mode()` and `get_current_display_mode()`
ysbaddaden/sdl.cr pull request #54
Opened 2022-08-23 21:39 UTC by bastienleonard

(Maybe these should go in a new `video` file? SDL's wiki lists them under the Video category.)

2022-08-25 00:11 UTC, bastienleonard commented
Reworked the commit and MR to include Window.display_index, which is necessary to use the other two functions.

2022-08-30 07:46 UTC, ysbaddaden requested changes
What about dropping the `get_` prefixes, so that we'd have `SDL.desktop_display_mode` and `SDL.current_display_mode`?

I'm wondering whether there could be a single function and a DisplayMode enum (Desktop, Current), so we'd call `SDL.display_mode(:current, 0)` and `SDL.display_mode(:desktop, 0)` for example, but that's probably overkill.

2022-08-30 07:46 UTC, ysbaddaden commented on src/sdl.cr
> +    ret = LibSDL.get_desktop_display_mode(0, out mode)
```suggestion
    ret = LibSDL.get_desktop_display_mode(display_index, out mode)
```

2022-08-30 07:46 UTC, ysbaddaden commented on src/sdl.cr
> +    ret = LibSDL.get_current_display_mode(0, out mode)
```suggestion
    ret = LibSDL.get_current_display_mode(display_index, out mode)
```

2022-09-01 00:37 UTC, bastienleonard commented
I made the changes that you requested. I was hoping that GitHub would update the diffs, but that doesn't to be the case.

>What about dropping the get_ prefixes, so that we'd have SDL.desktop_display_mode and SDL.current_display_mode?

Personally I generally prefer that functions don't have names that would be typical of attributes. But it depends on the convention you're using for the project, so it's your call.

>I'm wondering whether there could be a single function and a DisplayMode enum (Desktop, Current), so we'd call SDL.display_mode(:current, 0) and SDL.display_mode(:desktop, 0) for example, but that's probably overkill.

Personally I find that SDL2 is well designed overall for a C library and I prefer when bindings just adapt to the target language's idions. For example, in Rust I prefer to use the sys library that is just an unsafe wrapper around the C API, rather the full-fledged API which changes everything for no apparent reason.

2022-09-01 09:41 UTC, ysbaddaden commented
I'm following Ruby/Crystal practice of avoiding the get/set/is/has prefixes when possible:

- `get_name` -> `name`
- `set_name` -> `name=`
- `has_name` -> `name?`

For example `window.cr` is full of these.

2022-09-03 05:33 UTC, bastienleonard commented
If the goal is to make the method look like an attribute, then that seems in conflict with the fact that it takes a parameter (the display index).

I have added a commit with an alternative API. Typical usage would become `SDL.desktop_display_modes[window.display_index]`. One downside is that it makes the API slightly magical, which will confuse users if the abstraction leaks (e.g. in case of SDL error, users will have to realize it's not an actual array).

2022-09-07 21:59 UTC, bastienleonard commented
Sounds good, I removed the proposal commit and added a new one where I started working on the new API.

2022-10-10 22:37 UTC, bastienleonard commented
Can you give me feedback on the last commit?

2022-10-11 07:43 UTC, ysbaddaden approved these changes

2022-10-11 07:43 UTC, merged

2022-10-11 07:44 UTC, ysbaddaden commented
Thanks!